[package]
name = "luxarust"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.13.2"
luxarust_graphics = { version = "0.1.0", path = "../../luxarust_graphics" }
luxarust_system = { version = "0.1.0", path = "../luxarust_system" }
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader"] }
